name: Retry Deploy on Failure

on:
  workflow_run:
    workflows: ["Deploy"] # Name of main workflow
    types:
      - completed

jobs:
  retry:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow again
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TRIGGER_PAT }}
          event-type: retry-deploy
          repository: PedroBonorin0/ci_explorer/.github/workflows/main.yml@main
